-- Characters Data
CHARACTERS = {}

-- Categories with their names and colors
CHARACTERS.Categories = {
    {name = "Students", color = Color(0, 107, 0, 255)},
    {name = "Residents", color = Color(0, 107, 0, 255)},
    {name = "Demons", color = Color(153, 0, 0, 255)},
    {name = "Persona 2", color = Color(139, 0, 139, 255)},
    {name = "Persona 3", color = Color(25, 25, 170, 255)},
    {name = "Persona 4", color = Color(255, 229, 44, 255)},
    {name = "Persona 5", color = Color(153, 0, 0, 255)},
    {name = "Persona 5 X", color = Color(153, 0, 0, 255)},
    {name = "Soul Hackers 2", color = Color(203, 225, 49, 255)},
    {name = "Shin Megami Tensei V", color = Color(205, 199, 103, 255)},
    {name = "Visitors", color = Color(0, 107, 0, 255)},
    {name = "Unknown (HIGHLY DANGEROUS)", color = Color(153, 0, 0, 255)}
}

-- Characters list (separate from categories)
CHARACTERS.List = {
    -- UNKNOWN (HIGHLY DANGEROUS)
    ["amelia_watson"] = {
        name = "Watson Amelia",
        color = Color(255, 229, 44, 255),
        model = {"models/amelia_watson/hololive/rstar/amelia_watson/amelia_watson.mdl"},
        description = [[Watson Amelia (ワトソン・アメリア) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Ninomae Ina'nis, Takanashi Kiara, Mori Calliope and Gawr Gura.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "ame_timeskip",
            "ame_concoction"
        },
        essence = 20,
        command = "ame",
        type = "Boss",
        category = "Unknown (HIGHLY DANGEROUS)",
        max = 1,
        turns = 2,
        salary = 150,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 250,
        combatMP = 250,
        Luck = 6,
        Technique = 60,
        resist = {"Nuke"},
        weak = {"Gun"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ashley_williams"] = {
        name = "Ashley Williams",
        color = Color(20, 150, 20, 255),
        model = {"models/splinks/ash_williams/ash.mdl"},
        description = [[A Devil Summo- wtf]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "ash_mygun"},
        command = "ashley_williams",
        type = "Boss",
        category = "Unknown (HIGHLY DANGEROUS)",
        max = 1,
        turns = 2,
        salary = 150,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 500,
        combatMP = 0,
        Luck = 6,
        Technique = 60,
        resist = {"Dark"},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["skeletor"] = {
        name = "Skeletor",
        color = Color(20, 150, 20, 255),
        model = {
            "models/jqueary/callofduty/warzone2/ops/halloween/skeletor_sk_iw9_1_1_gmod.mdl",
            "models/masters_of_the_universe_vr/skeletor.mdl"
        },
        description = [[I'm going to answer the call of duty to end your life he-man -skeletor]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "skeletor_parabellum"},
        command = "skeletor",
        type = "Boss",
        category = "Unknown (HIGHLY DANGEROUS)",
        max = 1,
        turns = 2,
        salary = 150,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 500,
        combatMP = 0,
        Luck = 66,
        Technique = 66,
        resist = {"Evil"},
        weak = {"He-Man"},
        block = {},
        drain = {},
        repel = {}
    },
    -- STUDENTS
    ["student_a"] = {
        name = "Gekkoukan High School Student A",
        color = Color(20, 150, 20, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student who attends Gekkoukan High School. They innately share the potential to awakening Personas. These students have more affinity with magic.]],
        weapons = {"smti_engageswep", "smti_unarmedfists"},
        loadoutItems = {"persona_jackfrost", "persona_pixie"},
        essence = 1,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "students_a",
        type = "Human",
        race = "student",
        category = "Students",
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["student_b"] = {
        name = "Gekkoukan High School Student B",
        color = Color(20, 150, 20, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student who attends Gekkoukan High School. They innately share the potential to awakening Personas. These students have more affinity with physicality.]],
        weapons = {"smti_engageswep", "smti_unarmedfists"},
        loadoutItems = {"persona_jackfrost", "persona_pixie"},
        essence = 1,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "students_b",
        type = "Human",
        race = "student",
        category = "Students",
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 100,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    -- RESIDENTS
    ["citizen"] = {
        name = "Citizen",
        color = Color(20, 150, 20, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An adult who lives in or is visiting Tatsumi Port Island. They innately share the potential to awakening Personas.]],
        weapons = {"smti_engageswep", "smti_unarmedfists"},
        loadoutItems = {"persona_jackfrost", "persona_pixie"},
        essence = 1,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "citizen",
        type = "Human",
        race = "citizen",
        category = "Residents",
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["citizen_b"] = {
        name = "Citizen B",
        color = Color(20, 150, 20, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student who attends Gekkoukan High School. They innately share the potential to awakening Personas. These students have more affinity with physicality.]],
        weapons = {"smti_engageswep", "smti_unarmedfists"},
        loadoutItems = {"persona_jackfrost", "persona_pixie"},
        essence = 1,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "citizen_b",
        type = "Human",
        race = "citizen",
        category = "Residents",
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 100,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    -- TODO: SWITCH DESCRIPTION IF LORE CHANGES.
    ["police_officer"] = {
        name = "Police Officer",
        color = Color(20, 150, 20, 255),
        model = {"models/blacksurvival_nk/jenny/jenny_bs.mdl"},
        description = [[An officer serving duty at Tatsumi Port Island. They are responsible for peacekeeping and looking out for any trouble, particularly those caused by unruly folks or demons that sneak into the mainland.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_ebonytonfa",
            "smti_nambutype100"
        },
        equipmentSlots = 15,
        itemSlots = 10,
        command = "police_officer",
        type = "Police",
        race = "citizen",
        category = "Residents",
        max = 25,
        turns = 1,
        salary = 10,
        interval = 10,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 64,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["dsr_pmc"] = {
        name = "D.S.R PMC",
        color = Color(20, 150, 20, 255),
        model = {"models/blacksurvival_nk/jenny/jenny_bs.mdl"},
        description = [[A PMC contractor hired into the Demon Summoning Response unit funded by the government in response to the "rare sightings" of demon outbreaks. They specialize specifically in heavy firepower that cannot be found commonly, but cannot operate outside of the city effectively until further notice. Cannot acquire Personas or skill cards. Can infinitely restock grenades in police station.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_cm16",
            "smti_sras",
            "smti_rambus92fs",
            "smti_tabar",
            "smti_grenade",
            "smti_dsrrifle",
            "smti_prisonerdiamondformation"
        },
        equipmentSlots = 15,
        itemSlots = 10,
        command = "dsr_pmc",
        type = "Police",
        race = "citizen",
        category = "Residents",
        canUsePersonas = 0,
        canGetSkills = 0,
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 10,
        Luck = 10,
        Technique = 65,
        resist = {"Physical"},
        weak = {"Dark", "Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    -- VISITORS
    ["demi_fiend"] = {
        name = "Demi-Fiend",
        color = Color(0, 107, 0, 255),
        model = {"models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"},
        description = [[A high school student cursed with the body of a demon holding a human heart. The Demi-fiend is one born with odds built against him, but his potential even more terrifying than said odds.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_lunge_demi",
            "smti_javelinrain",
            "smti_magmaaxis"
        },
        command = "demi_fiend",
        type = "Human",
        race = "student",
        category = "Visitors",
        canUsePersonas = 0,
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        noPersonas = true,
        combatHP = 400,
        combatMP = 140,
        Luck = 6,
        Technique = 50,
        resist = {"Dark"},
        weak = {"Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    -- SHIN MEGAMI TENSEI V
    ["nahobino"] = {
        name = "Nahobino",
        color = Color(205, 199, 103, 255),
        model = {"models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"},
        description = [[A high school student from Jouin High School. When fused with the Proto-fiend, Aogami, he becomes a Nahobino.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_protosword",
            "smti_miraclewater",
            "smti_omagatokicritical",
            "smti_thalassiccalamity"
        },
        command = "nahobino",
        type = "Human",
        race = "student",
        category = "Shin Megami Tensei V",
        canUsePersonas = 0,
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        noPersonas = true,
        combatHP = 365,
        combatMP = 150,
        Luck = 10,
        Technique = 58,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    -- PERSONA 2
    ["tatsuya_suou"] = {
        name = "Tatsuya Suou",
        color = Color(139, 0, 139, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl"
        },
        description = [[He's a senior student enrolling in Seven Sisters High School in Sumaru City. He has an older brother named Katsuya Suou, a police detective. Tatsuya also has an unnamed father.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_novakaiser",
            "smti_twohandedsword"
        },
        command = "tatsuya_suou",
        type = "Human",
        race = "persona_user",
        category = "Persona 2",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Ice"},
        block = {},
        drain = {},
        repel = {}
    },
    ["lisa_silverman"] = {
        name = "Lisa Silverman",
        color = Color(139, 0, 139, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl"
        },
        description = [[A student at Seven Sisters High School, temporarily enrolled in Gekkoukan High School. She is greatly interested in martial arts with natural charisma to back her up.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_kozanofthenorth",
            "smti_foamylover"
        },
        command = "lisa_silverman",
        type = "Human",
        race = "persona_user",
        category = "Persona 2",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {"Light"},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    ["eikichi_mishina"] = {
        name = "Eikichi Mishina",
        color = Color(139, 0, 139, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl"
        },
        description = [[KAZUYA MISHIMA is a student at Kasugayama High School, temporarily enrolled in Gekkoukan High School. She is greatly interested in martial arts with natural charisma to back her up.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_cm16",
            "smti_bloodyhoneymoon"
        },
        command = "eikichi_mishina",
        type = "Human",
        race = "persona_user",
        category = "Persona 2",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 320,
        combatMP = 180,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["maya_amano"] = {
        name = "Maya Amano",
        color = Color(139, 0, 139, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl"
        },
        description = [[Maya is a young woman in her early twenties with light skin, shoulder-length black hair styled in a flip, and purple eyes.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_absolutezero"},
        command = "maya_amano",
        type = "Human",
        race = "persona_user",
        category = "Persona 2",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 15,
        Technique = 55,
        resist = {"Magic"},
        weak = {"Physical"},
        block = {},
        drain = {},
        repel = {}
    },
    ["jun_kurosu"] = {
        name = "Jun Kurosu",
        color = Color(139, 0, 139, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl"
        },
        description = [[As a student of Kasugayama High School, Jun is usually seen wearing the school's light blue gakuran-style uniform with black loafers. He wears the silver wristwatch he received from Tatsuya on his left, and a yellow iris in the buttonhole of his jacket.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_crossfortune"},
        command = "jun_kurosu",
        type = "Human",
        race = "persona_user",
        category = "Persona 2",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 15,
        Technique = 55,
        resist = {},
        weak = {"Nuke"},
        block = {"Wind"},
        drain = {},
        repel = {}
    },
    -- PERSONA 3
    ["makoto_yuki"] = {
        name = "Makoto Yuki",
        color = Color(25, 25, 170, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/smt_nk/smtif/smtif_erbsf.mdl",
            "models/smt_nk/smtif/smtif_erbsm.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl",
            "models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"
        },
        description = [[A transfer student enrolling in Gekkoukan High School in Iwatodai City. An active member of SEES.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_cadenza",
            "smti_twohandedsword"
        },
        command = "makoto_yuki",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["kotone_shiomi"] = {
        name = "Kotone Shiomi",
        color = Color(25, 25, 170, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/smt_nk/smtif/smtif_erbsf.mdl",
            "models/smt_nk/smtif/smtif_erbsm.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl",
            "models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"
        },
        description = [[A transfer student enrolling in Gekkoukan High School in Iwatodai City. An active member of SEES. (Alternate Name: Minako Arisato)]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_healingharp",
            "smti_lanceofvitality"
        },
        command = "kotone_shiomi",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["junpei_iori"] = {
        name = "Junpei Iori",
        color = Color(25, 25, 170, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/smt_nk/smtif/smtif_erbsf.mdl",
            "models/smt_nk/smtif/smtif_erbsm.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl",
            "models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"
        },
        description = [[A student enrolling in Gekkoukan High School in Iwatodai City with a fondness for baseball. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_damascussword"},
        permaBuffs = {
            ["Triangle_Drill"] = {
                stacks = 1,
                type = "kill",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_triangledrill"
            }
        },
        command = "junpei_iori",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 375,
        combatMP = 125,
        Luck = 7,
        Technique = 56,
        resist = {},
        weak = {"Wind"},
        block = {},
        drain = {},
        repel = {}
    },
    ["yukari_takeba"] = {
        name = "Yukari Takeba",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolling in Gekkoukan High School in Iwatodai City with a fondness for archery and acting. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_hankyu"},
        permaBuffs = {
            ["Anchor_Point"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_anchorpoint"
            }
        },
        command = "yukari_takeba",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 175,
        Luck = 8,
        Technique = 64,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    ["mitsuru_kirijo"] = {
        name = "Mitsuru Kirijo",
        color = Color(25, 25, 170, 255),
        model = {
            "models/player/dewobedil/kancolle/murasame/default_p.mdl",
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/smt_nk/smtif/smtif_erbsf.mdl",
            "models/smt_nk/smtif/smtif_erbsm.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl",
            "models/pacagma/smt_n/hitoshura/hitoshura_player.mdl"
        },
        description = [[Gekkoukan High School's valedictorian and student council president, as well as a member of the school fencing club. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_schiavona"},
        permaBuffs = {
            ["Third_Intention"] = {
                stacks = 1,
                type = "kill",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_thirdintention"
            }
        },
        command = "mitsuru_kirijo",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 330,
        combatMP = 170,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["akihiko_sanada"] = {
        name = "Akihiko Sanada",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolling in Gekkoukan High School in Iwatodai City. He is the captain of the boxing team. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_kozanofthesouth"},
        permaBuffs = {
            ["Eight_Count"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_eightcount"
            }
        },
        command = "akihiko_sanada",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 360,
        combatMP = 140,
        Luck = 9,
        Technique = 62,
        resist = {},
        weak = {"Ice"},
        block = {},
        drain = {},
        repel = {}
    },
    ["fuuka_yamagishi"] = {
        name = "Fuuka Yamagishi",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolling in Gekkoukan High School in Iwatodai City with a fondness for computers and technology. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_papillondiabolos"},
        permaBuffs = {
            ["Healing_Wave"] = {
                stacks = 1,
                type = "victory",
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_healingwave"
            }
        },
        command = "fuuka_yamagishi",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 315,
        combatMP = 185,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ken_amada"] = {
        name = "Ken Amada",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolling in Gekkoukan High School in Iwatodai City. He is the captain of the boxing team. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_spear"},
        permaBuffs = {
            ["Premonition"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_premonition"
            }
        },
        command = "ken_amada",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 170,
        Luck = 8,
        Technique = 55,
        resist = {},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    ["koromaru"] = {
        name = "Koromaru",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A Shiba Inu in Iwatodai City currently taken in by the SEES with the potential to summon Personas through a special Evoker. An active member of SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_randallknife"},
        permaBuffs = {
            ["Shrine_Guardian"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_shrineguardian"
            }
        },
        command = "koromaru",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 320,
        combatMP = 170,
        Luck = 13,
        Technique = 55,
        resist = {},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["shinjiro_aragaki"] = {
        name = "Shinjiro Aragaki",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A senior student enrolling in Gekkoukan High School in Iwatodai City. He is one of the first members of the SEES.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_tabar"},
        permaBuffs = {
            ["Suppressor"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_suppressor"
            }
        },
        command = "shinjiro_aragaki",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 380,
        combatMP = 120,
        Luck = 4,
        Technique = 60,
        resist = {},
        weak = {"Bow"},
        block = {},
        drain = {},
        repel = {}
    },
    ["aigis"] = {
        name = "Aigis",
        color = Color(25, 25, 170, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An Anti-Shadow Suppression Weapon attending Gekkoukan High School. An active member of SEES.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_cm16",
            "smti_orgiamode"
        },
        permaBuffs = {
            ["Papillon_Heart"] = {
                stacks = 1,
                type = "reactionHeal",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_papillonheart"
            }
        },
        command = "aigis",
        type = "Human",
        race = "sees",
        category = "Persona 3",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {"Bow", "Gun"},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    -- PERSONA 4
    ["yu_narukami"] = {
        name = "Yu Narukami",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A transfer student at Yasogami High School, temporarily enrolled in Gekkoukan High School. An active member of the Investigation Team.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_twohandedsword",
            "smti_lensoftruth"
        },
        command = "yu_narukami",
        type = "Human",
        race = "investigation_team",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 340,
        combatMP = 160,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Wind"},
        block = {},
        drain = {},
        repel = {}
    },
    ["rise_kujikawa"] = {
        name = "Rise Kujikawa",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A popular idol who returns to Inaba for a brief hiatus. She is a first-year student at Yasogami High School.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_encore",
            "smti_enkanohanamichi",
            "smti_elecrush",
            "smti_twinklestar"
        },
        command = "rise_kujikawa",
        type = "Human",
        race = "student",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 315,
        combatMP = 190,
        Luck = 10,
        Technique = 55,
        resist = {},
        weak = {"Gun", "Physical"},
        block = {},
        drain = {},
        repel = {}
    },
    ["yukiko_amagi"] = {
        name = "Yukiko Amagi",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[She is the protagonist's classmate at Yasogami High School, and her family runs Inaba's hot springs inn called the Amagi Inn where she is next in-line as manager.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_ironfanoftheempress",
            "smti_firerush",
            "smti_phoenixgust"
        },
        permaBuffs = {
            ["Cauterizing_Flames"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_cauterizingflames"
            }
        },
        command = "yukiko_amagi",
        type = "Human",
        race = "student",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 210,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Ice"},
        block = {},
        drain = {},
        repel = {}
    },
    ["chie_satonaka"] = {
        name = "Chie Satonaka",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An energetic girl with a love of kung-fu movies, she's one of the protagonist's classmates at Yasogami High School.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_ebonytonfa",
            "smti_dragonkick",
            "smti_physrush",
            "smti_trialofthedragon"
        },
        command = "chie_satonaka",
        type = "Human",
        race = "student",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 100,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["yosuke_hanamura"] = {
        name = "Yosuke Hanamura",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[He is the protagonist's classmate at Yasogami High School in Inaba and the son of the Junes Department Store's Inaba branch manager.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_forcerush",
            "smti_herofromjunes"
        },
        permaBuffs = {
            ["Sukukaja"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_autosukukaja"
            }
        },
        command = "yosuke_hanamura",
        type = "Human",
        race = "student",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 150,
        Luck = 10,
        Technique = 65,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    ["naoto_shirogane"] = {
        name = "Naoto Shirogane",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[The fifth generation of the famed Shirogane detectives, Naoto arrives in Inaba to help investigate the murders, and enrolls as a first-year student at Yasogami High School.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_nambutype100",
            "smti_aimstance",
            "smti_darkrush",
            "smti_lockedon"
        },
        command = "naoto_shirogane",
        type = "Human",
        race = "police",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 175,
        Luck = 12,
        Technique = 55,
        resist = {},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["kanji_tatsumi"] = {
        name = "Kanji Tatsumi",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student at Yasogami High School, temporarily enrolled in Gekkoukan High School. An active member of the Investigation Team.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_nobell",
            "smti_kabutsuchikyoko"
        },
        command = "kanji_tatsumi",
        type = "Human",
        race = "investigation_team",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 380,
        combatMP = 120,
        Luck = 12,
        Technique = 58,
        resist = {},
        weak = {"Wind"},
        block = {},
        drain = {},
        repel = {}
    },
    ["teddie_kuma"] = {
        name = "Teddie (Kuma)",
        color = Color(255, 229, 44, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A mascot bear with two forms that also seems to be an active member of the Investigation Team.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_kamuimiracle"},
        command = "teddie_kuma",
        type = "Human",
        race = "investigation_team",
        category = "Persona 4",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 310,
        combatMP = 190,
        Luck = 14,
        Technique = 56,
        resist = {"Ice"},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    -- PERSONA 5
    ["ren_amamiya"] = {
        name = "Ren Amamiya (Joker)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A transfer student enrolled in Shujin Academy and temporarily attending Gekkoukan High School in Iwatodai City. An active member of the Phantom Thieves.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_randallknife"},
        permaBuffs = {
            ["Pinch_Anchor"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_pinchanchor"
            }
        },
        command = "ren_amamiya",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ryuji_sakamoto"] = {
        name = "Ryuji Sakamoto",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Harlot]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_ironpipe",
            "smti_physrush",
            "smti_eccentrictemper"
        },
        permaBuffs = {
            ["Raging_Temper"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_ragingtemper"
            }
        },
        command = "ryuji_sakamoto",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 100,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Wind"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ann_takamaki"] = {
        name = "Ann Takamaki",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Harlot]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_gildedwhip",
            "smti_firerush"
        },
        permaBuffs = {
            ["Mastery_of_Magic"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_masteryofmagic"
            }
        },
        command = "ann_takamaki",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 310,
        combatMP = 190,
        Luck = 15,
        Technique = 55,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    ["morgana"] = {
        name = "Morgana",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[He is a mysterious being with ties to Mementos. He doesn't know who he is, and seeks answers to restore his memories.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_forcerush",
            "smti_majesticpresence"
        },
        permaBuffs = {
            ["Proud_Presence"] = {
                stacks = 1,
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_proudpresence"
            }
        },
        command = "morgana",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    ["yusuke_kitagawa"] = {
        name = "Yusuke Kitagawa",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[it doesn't give me enough for this tbh]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_yanagiba",
            "smti_icerush",
            "smti_unparalleledeyes"
        },
        permaBuffs = {
            ["Scoundrel_Eyes"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_scoundreleyes"
            }
        },
        command = "yusuke_kitagawa",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 175,
        Luck = 5,
        Technique = 65,
        resist = {},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["makoto_niijima"] = {
        name = "Makoto Niijima",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[She's the student council president of Shujin Academy who lives a double life as a Phantom Thief.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_nukerush",
            "smti_gaiablessing"
        },
        permaBuffs = {
            ["Gaia_Pact"] = {
                stacks = 1,
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_gaiapact"
            }
        },
        command = "makoto_niijima",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 400,
        combatMP = 100,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    ["haru_okumura"] = {
        name = "Haru Okumura",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[uh i legit don't have any for this one.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_ruinrush",
            "smti_coolcustomer"
        },
        permaBuffs = {
            ["Icy_Glare"] = {
                stacks = 1,
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_icyglare"
            }
        },
        command = "haru_okumura",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Nuke"},
        block = {},
        drain = {},
        repel = {}
    },
    ["futaba_sakura"] = {
        name = "Futaba Sakura",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[uh i legit don't have any for this one.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_grenade"},
        permaBuffs = {
            ["Explosive_Scheme"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_explosivescheme"
            }
        },
        command = "futaba_sakura",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 300,
        Luck = 20,
        Technique = 50,
        resist = {},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    ["sumire_yoshizawa"] = {
        name = "Sumire Yoshizawa",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[She is a first-year transfer student at Shujin Academy and a talented gymnast who gets involved with the Phantom Thieves of Hearts.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_icerush",
            "smti_veilofsunrise"
        },
        permaBuffs = {
            ["Veil_of_Midnight"] = {
                stacks = 1,
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_veilofmidnight"
            }
        },
        command = "sumire_yoshizawa",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    -- PERSONA 5 X
    ["wonder"] = {
        name = "Wonder",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. An active member of the Phantom Thieves.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_whitenight",
            "smti_gunfirerush",
            "smti_quickfocus"
        },
        permaBuffs = {
            ["Lock_On"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_lockon"
            }
        },
        command = "wonder",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["arai_motoha"] = {
        name = "Arai Motoha (Closer)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. An active member of the Phantom Thieves. The term "closer" refers to a baseball closing pitcher specializing on the final outs of a game.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_meteorhammer",
            "smti_elecrush",
            "smti_windup"
        },
        permaBuffs = {
            ["Closing_Pitch"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_closingpitch"
            }
        },
        command = "arai_motoha",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 340,
        combatMP = 160,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    ["kanou_shun"] = {
        name = "Kanou Shun (Soy)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. An active member of the Phantom Thieves. The term "soy" refers to soy sauce, a sauce favored by many Japanese chefs for robust flavors.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_steelhandaxe",
            "smti_rotarymachinegun",
            "smti_icerush",
            "smti_originalrecipe"
        },
        permaBuffs = {
            ["Omakase"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_omakase"
            }
        },
        command = "kanou_shun",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 380,
        combatMP = 120,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Ice"},
        block = {},
        drain = {},
        repel = {}
    },
    ["tomoko_noge"] = {
        name = "Tomoko Noge (Moko)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. A potential Phantom Idol. She has good experience with baseball and work ethic.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_randallknife",
            "smti_hankyu",
            "smti_purpleleaves",
            "smti_ruinrush",
            "smti_unwaveringsupport"
        },
        command = "tomoko_noge",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 15,
        Technique = 55,
        resist = {},
        weak = {"Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    ["riko_tanemura"] = {
        name = "Riko Tanemura (Wind)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. An active member of the Phantom Thieves. She is a Discipline Committee member of the academy.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_treasureringparasol",
            "smti_forcerush",
            "smti_twilightshadow"
        },
        command = "riko_tanemura",
        permaBuffs = {
            ["Bird_Song"] = {
                stacks = 1,
                targets = "party",
                visibility = 0,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_birdsong"
            }
        },
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 300,
        combatMP = 200,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Force"},
        block = {},
        drain = {},
        repel = {}
    },
    ["minami_miyashita"] = {
        name = "Minami Miyashita (Marian)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. A potential Phantom Idol. She dreams of becoming a nurse like her late mother one day and is known to help parents take care of their children in busy times.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_rambussvd",
            "smti_combatmedkit",
            "smti_lightrush",
            "smti_postoperativecare"
        },
        permaBuffs = {
            ["Benevolence"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_benevolence"
            }
        },
        command = "minami_miyashita",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 180,
        Luck = 8,
        Technique = 56,
        resist = {},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["yukimi_fujikawa"] = {
        name = "Yukimi Fujikawa (Yuki)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A student enrolled in Kokatsu Academy and temporarily attending Gekkoukan High School in Iwatodai City. A potential Phantom Idol. She seeks to become a lawyer rather than inheriting her mother's business.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_morningstar",
            "smti_dualpistols",
            "smti_lightrush",
            "smti_firmwill"
        },
        permaBuffs = {
            ["Devotion_of_Rebuttal"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_devotionofrebuttal"
            }
        },
        command = "yukimi_fujikawa",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 350,
        combatMP = 150,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Light"},
        block = {},
        drain = {},
        repel = {}
    },
    ["chizuko_nagao"] = {
        name = "Chizuko Nagao (Vino)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An elderly lady who likes drinking and can hold her liquor very well. A potential Phantom Idol. She is good at playing saxophone but has dropped it since her husband who was enthusiastic about music had passed away.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_tridagger",
            "smti_sweeper",
            "smti_nukerush",
            "smti_roaringengine"
        },
        permaBuffs = {
            ["Second_Serving"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_secondserving"
            }
        },
        command = "chizuko_nagao",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 280,
        combatMP = 220,
        Luck = 7,
        Technique = 65,
        resist = {},
        weak = {"Nuke"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ayaka_sakai"] = {
        name = "Ayaka Sakai (Chord)",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A college student who is also an amateur songwriter and singer. A potential Phantom Idol. She wishes to sing one day alongside her guitar playing skills.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_electricguitarassault",
            "smti_elecrush",
            "smti_accent"
        },
        permaBuffs = {
            ["Welcome_the_Dawn"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_welcomethedawn"
            }
        },
        command = "ayaka_sakai",
        type = "Human",
        race = "phantom_thieves",
        category = "Persona 5 X",
        equipmentSlots = 15,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 270,
        combatMP = 230,
        Luck = 10,
        Technique = 60,
        resist = {},
        weak = {"Elec"},
        block = {},
        drain = {},
        repel = {}
    },
    -- SOUL HACKERS 2
    ["ringo"] = {
        name = "Ringo",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An agent of Aion, a digital hivemind that exists in the sea of humanity's data. Though unfamiliar with human society and culture, she is arguably one of the most adept at handling long-standing conflicts.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_antikythera_ringo",
            "smti_shielddeployment",
            "smti_mpoptimization"
        },
        permaBuffs = {
            ["Sabbath"] = {
                stacks = 1,
                type = "bonusCritDamage",
                targets = "party",
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_sabbath"
            }
        },
        command = "ringo",
        type = "Human",
        race = "aion",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 175,
        Luck = 12,
        Technique = 55,
        resist = {"Elec"},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["figue"] = {
        name = "Figue",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[An agent of Aion, a digital hivemind that exists in the sea of humanity's data. Her ability in providing support through reconnaissance and analysis makes her valuable in gathering intel ahead of time.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_antikythera_figue",
            "smti_autorepair",
            "smti_overclock"
        },
        command = "figue",
        type = "Human",
        race = "aion",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 310,
        combatMP = 190,
        Luck = 16,
        Technique = 50,
        resist = {"Ruin"},
        weak = {},
        block = {},
        drain = {},
        repel = {}
    },
    ["arrow"] = {
        name = "Arrow",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A Devil Summoner from Yatagarasu. He was given a second chance by Ringo to find his own path to peace while investigating the recent surges in demon activity.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_mk90"},
        permaBuffs = {
            ["Soul_Matrix_Arrow"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_soulmatrixarrow"
            }
        },
        command = "arrow",
        type = "Human",
        race = "devil_summoner",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 340,
        combatMP = 160,
        Luck = 10,
        Technique = 60,
        resist = {"Ice"},
        weak = {"Gun"},
        block = {},
        drain = {},
        repel = {}
    },
    ["milady"] = {
        name = "Milady",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A Devil Summoner from the Phantom Society. A ruthless realist who is temporarily working with Ringo to discover the myriad of truths hidden behind the rapidly increasing demon activities.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_stigma"},
        permaBuffs = {
            ["Soul_Matrix_Milady"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_soulmatrixmilady"
            }
        },
        permaDebuffs = {["Soul_Matrix_Milady"] = {stacks = 1, visibility = 0}},
        command = "milady",
        type = "Human",
        race = "devil_summoner",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 360,
        combatMP = 140,
        Luck = 8,
        Technique = 62,
        resist = {"Fire"},
        weak = {"Martial Arts"},
        block = {},
        drain = {},
        repel = {}
    },
    ["saizo"] = {
        name = "Saizo",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A freelancer Devil Summoner. Though quick-witted and clever, he can be impulsive with purchases. He is often assisting Ringo during his off-time.]],
        weapons = {"smti_engageswep", "smti_unarmedfists", "smti_tommygun"},
        permaBuffs = {
            ["Soul_Matrix_Saizo"] = {
                stacks = 1,
                SlotsTaking = 1,
                SlotType = "Equipment",
                ClassName = "smti_soulmatrixsaizo"
            }
        },
        command = "saizo",
        type = "Human",
        race = "devil_summoner",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 330,
        combatMP = 170,
        Luck = 13,
        Technique = 57,
        resist = {"Force"},
        weak = {"Blade"},
        block = {},
        drain = {},
        repel = {}
    },
    ["ash"] = {
        name = "Ash",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A Devil Summoner from the Phantom Society. Though she could come off as dry, she has a caring, yet paranoid side to her.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_blackout",
            "smti_ashestoashes"
        },
        command = "ash",
        type = "Human",
        race = "devil_summoner",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 330,
        combatMP = 170,
        Luck = 13,
        Technique = 57,
        resist = {"Ruin"},
        weak = {"Force"},
        block = {},
        drain = {},
        repel = {}
    },
    ["nana"] = {
        name = "Nana",
        color = Color(203, 225, 49, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[A Devil Summoner with a rather ravenous appetite for food. Despite her laidback attitude, her prowess in battle is notably potent.]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_grenadehammer",
            "smti_nerfinator"
        },
        command = "nana",
        type = "Human",
        race = "devil_summoner",
        category = "Soul Hackers 2",
        equipmentSlots = 14,
        itemSlots = 10,
        max = 1,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 325,
        combatMP = 175,
        Luck = 10,
        Technique = 60,
        resist = {"Force"},
        weak = {"Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    -- DEMONS
    ["jack_frost_a"] = {
        name = "Jack Frost",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Variant A.

An elf-like creature who is the embodiment of all that is cold. It is said that he is the one who leaves those beautiful icy patterns on windows in the morning.
]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_jackbufula",
            "smti_icerush",
            "smti_physrush"
        },
        loadoutItems = {
            "Tarukaja_Universal",
            "Rakukaja_Universal",
            "Sukukaja_Universal",
            "Tarunda_Universal",
            "Rakunda_Universal",
            "Sukunda_Universal",
            "Dekaja_Universal",
            "Dekunda_Universal",
            "Posumudi_Universal",
            "Patra_Universal",
            "AmritaDrop_Universal",
            "LifeBonus_Universal",
            "LastResort_Standard",
            "Sacrifice_Standard",
            "Bufu_Standard",
            "Mabufu_Standard",
            "Hama_Standard",
            "Mahama_Standard",
            "Dia_Standard",
            "IceBoost_Standard"
        },
        essence = 200,
        kilodevil = 100,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "jackfrostA",
        type = "Demon",
        race = "fairy",
        category = "Demons",
        cantSeeMembers = true,
        max = 0,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 190,
        combatMP = 170,
        Luck = 10,
        Technique = 60,
        resist = {"Ice"},
        weak = {"Fire"},
        block = {},
        drain = {},
        repel = {}
    },
    ["jack_frost_b"] = {
        name = "Jack Frost",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Variant B.

An elf-like creature who is the embodiment of all that is cold. It is said that he is the one who leaves those beautiful icy patterns on windows in the morning.
]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_jackbufula",
            "smti_icerush",
            "smti_physrush"
        },
        loadoutItems = {
            "Tarukaja_Universal",
            "Rakukaja_Universal",
            "Sukukaja_Universal",
            "Tarunda_Universal",
            "Rakunda_Universal",
            "Sukunda_Universal",
            "Dekaja_Universal",
            "Dekunda_Universal",
            "Posumudi_Universal",
            "Patra_Universal",
            "AmritaDrop_Universal",
            "LifeBonus_Universal",
            "LastResort_Standard",
            "Sacrifice_Standard",
            "Bufu_Standard",
            "Mabufu_Standard",
            "Hama_Standard",
            "Mahama_Standard",
            "Dia_Standard",
            "IceBoost_Standard"
        },
        essence = 200,
        kilodevil = 100,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "jackfrostB",
        type = "Demon",
        race = "fairy",
        category = "Demons",
        cantSeeMembers = true,
        max = 0,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 175,
        combatMP = 175,
        Luck = 13,
        Technique = 62,
        resist = {"Light"},
        weak = {"Dark"},
        block = {},
        drain = {},
        repel = {}
    },
    ["pixie_a"] = {
        name = "Pixie",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Variant A.

A small fairy found in southwestern Britain known for their cheerful nature and love of pranks. Their physical appearance changes from region to region, but their personality is always playful and mischievous. A common prank they like to pull is causing humans to wander in circles. However, they are also known to help farmers from time to time and are generally considered good fairies.
]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_fortunekiss",
            "smti_elecrush",
            "smti_ruinrush"
        },
        loadoutItems = {
            "Tarukaja_Universal",
            "Rakukaja_Universal",
            "Sukukaja_Universal",
            "Tarunda_Universal",
            "Rakunda_Universal",
            "Sukunda_Universal",
            "Dekaja_Universal",
            "Dekunda_Universal",
            "Posumudi_Universal",
            "Patra_Universal",
            "AmritaDrop_Universal",
            "LifeBonus_Universal",
            "LastResort_Standard",
            "Sacrifice_Standard",
            "Agi_Standard",
            "Bufu_Standard",
            "Zio_Standard",
            "Mazio_Standard",
            "Zan_Standard",
            "Mazan_Standard",
            "MarinKarin_Standard",
            "MePatra_Standard",
            "Dia_Standard",
            "Media_Standard"
        },
        essence = 200,
        kilodevil = 100,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "pixieA",
        type = "Demon",
        race = "fairy",
        category = "Demons",
        cantSeeMembers = true,
        max = 0,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 200,
        combatMP = 160,
        Luck = 10,
        Technique = 60,
        resist = {"Wind", "Ruin"},
        weak = {"Elec", "Nuke"},
        block = {},
        drain = {},
        repel = {}
    },
    ["pixie_b"] = {
        name = "Pixie",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Variant B.

A small fairy found in southwestern Britain known for their cheerful nature and love of pranks. Their physical appearance changes from region to region, but their personality is always playful and mischievous. A common prank they like to pull is causing humans to wander in circles. However, they are also known to help farmers from time to time and are generally considered good fairies.
]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_fortunekiss",
            "smti_elecrush",
            "smti_ruinrush"
        },
        loadoutItems = {
            "Tarukaja_Universal",
            "Rakukaja_Universal",
            "Sukukaja_Universal",
            "Tarunda_Universal",
            "Rakunda_Universal",
            "Sukunda_Universal",
            "Dekaja_Universal",
            "Dekunda_Universal",
            "Posumudi_Universal",
            "Patra_Universal",
            "AmritaDrop_Universal",
            "LifeBonus_Universal",
            "LastResort_Standard",
            "Sacrifice_Standard",
            "Agi_Standard",
            "Bufu_Standard",
            "Zio_Standard",
            "Mazio_Standard",
            "Zan_Standard",
            "Mazan_Standard",
            "MarinKarin_Standard",
            "MePatra_Standard",
            "Dia_Standard",
            "Media_Standard"
        },
        essence = 200,
        kilodevil = 100,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "pixieB",
        type = "Demon",
        race = "fairy",
        category = "Demons",
        cantSeeMembers = true,
        max = 0,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 180,
        combatMP = 180,
        Luck = 12,
        Technique = 62,
        resist = {"Fire", "Elec"},
        weak = {"Gun", "Ruin"},
        block = {},
        drain = {},
        repel = {}
    },
    ["inugami_a"] = {
        name = "Inugami",
        color = Color(153, 0, 0, 255),
        model = {
            "models/blacksurvival_nk/jenny/jenny_bs.mdl",
            "models/blacksurvival_nk/jenny/jennyskin_bs.mdl",
            "models/blacksurvival_nk/cathy/cathy_bs.mdl"
        },
        description = [[Variant A.

A dog spirit said to possess people in Japanese lore. Those possessed are in a state of "inu-tsuki" and lose consciousness. Onmyoji use Inugami as familiars.
]],
        weapons = {
            "smti_engageswep",
            "smti_unarmedfists",
            "smti_firerush",
            "smti_physrush"
        },
        loadoutItems = {
            "Tarukaja_Universal",
            "Rakukaja_Universal",
            "Sukukaja_Universal",
            "Tarunda_Universal",
            "Rakunda_Universal",
            "Sukunda_Universal",
            "Dekaja_Universal",
            "Dekunda_Universal",
            "Posumudi_Universal",
            "Patra_Universal",
            "AmritaDrop_Universal",
            "LifeBonus_Universal",
            "LastResort_Standard",
            "Sacrifice_Standard",
            "Agi_Standard",
            "Maragi_Standard",
            "FireBreath_Standard",
            "Zio_Standard",
            "Shibaboo_Standard",
            "DreamNeedle_Standard",
            "TripleDown_Standard",
            "GiantSlice_Standard",
            "ResistDark_Standard"
        },
        permaBuffs = {
            ["Tansu_of_Vengeance"] = {
                stacks = 1,
                SlotsTaking = 1,
                visibility = 0,
                SlotType = "Equipment",
                ClassName = "smti_tansuofvengeance"
            }
        },
        essence = 200,
        kilodevil = 100,
        equipmentSlots = 15,
        itemSlots = 10,
        command = "inugamiA",
        type = "Demon",
        race = "beast",
        category = "Demons",
        cantSeeMembers = true,
        max = 25,
        turns = 1,
        salary = 0,
        admin = 0,
        vote = false,
        hasLicense = false,
        combatHP = 250,
        combatMP = 110,
        Luck = 10,
        Technique = 60,
        resist = {"Gun"},
        weak = {"Force", "Light"},
        block = {"Fire"},
        drain = {},
        repel = {}
    }
}
